import { NextResponse } from 'next/server'
import { requireSameOrigin } from '@/lib/security'
import { z } from 'zod'
import { createSupabaseServerClient } from '@/lib/supabase-server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
const schema = z.object({ name: z.string().min(2).max(160), email: z.string().email().max(320), phone: z.string().max(50).optional().nullable(), notes: z.string().max(2000).optional().nullable() })
async function ctx(){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return {error:NextResponse.json({error:'Non autenticato'},{status:401})};const admin=getSupabaseAdmin();if(!admin)return {error:NextResponse.json({error:'Supabase server non configurato'},{status:500})};const {data:member}=await admin.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1).maybeSingle();if(!member)return {error:NextResponse.json({error:'Organizzazione non configurata'},{status:400})};return {admin,orgId:member.organization_id,user}}
export async function GET(req:Request){const c=await ctx();if('error'in c)return c.error;const q=new URL(req.url).searchParams.get('q')?.trim()||'';let query=c.admin.from('clients').select('id,name,email,phone,created_at').eq('organization_id',c.orgId).is('deleted_at',null).order('name');if(q)query=query.or(`name.ilike.%${q.replace(/[%_]/g,'')}%,email.ilike.%${q.replace(/[%_]/g,'')}%`);const {data,error}=await query;if(error)return NextResponse.json({error:error.message},{status:500});const ids=(data||[]).map((x:any)=>x.id);let counts:Record<string,number>={};if(ids.length){const {data:cases}=await c.admin.from('cases').select('client_id').eq('organization_id',c.orgId).in('client_id',ids);for(const row of cases||[])counts[row.client_id]=(counts[row.client_id]||0)+1}return NextResponse.json({clients:(data||[]).map((x:any)=>({...x,caseCount:counts[x.id]||0}))})}
export async function POST(req:Request){
  const originError=requireSameOrigin(req); if(originError)return originError
  const body=schema.safeParse(await req.json().catch(()=>null));if(!body.success)return NextResponse.json({error:'Dati cliente non validi'},{status:400});const c=await ctx();if('error'in c)return c.error;const {data,error}=await c.admin.from('clients').insert({organization_id:c.orgId,name:body.data.name,email:body.data.email,phone:body.data.phone||null,notes:body.data.notes||null}).select('id,name,email,phone').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({client:data})}
