import { NextResponse } from 'next/server'
import { z } from 'zod'
import { createSupabaseServerClient } from '@/lib/supabase-server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import { requireSameOrigin, rateLimit } from '@/lib/security'
const schema=z.object({body:z.string().trim().min(1).max(4000)})
async function ctx(){const s=await createSupabaseServerClient();const {data:{user}}=await s.auth.getUser();if(!user)return{error:NextResponse.json({error:'Autenticazione richiesta'},{status:401})};const admin=getSupabaseAdmin();if(!admin)return{error:NextResponse.json({error:'Supabase server non configurato'},{status:503})};const {data:member}=await admin.from('organization_members').select('organization_id,role').eq('user_id',user.id).limit(1).maybeSingle();if(!member||!['owner','admin'].includes(member.role))return{error:NextResponse.json({error:'Permesso insufficiente'},{status:403})};return{admin,orgId:member.organization_id,user}}
export async function GET(_req:Request,{params}:{params:Promise<{id:string}>}){const c=await ctx();if('error'in c)return c.error;const {id}=await params;const {data,error}=await c.admin.from('portal_messages').select('id,sender_type,body,created_at').eq('organization_id',c.orgId).eq('case_id',id).order('created_at',{ascending:true}).limit(100);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({messages:data||[]})}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const originError=requireSameOrigin(req);if(originError)return originError;const limited=rateLimit(req,'case-messages',30,60*60*1000);if(limited)return limited;const c=await ctx();if('error'in c)return c.error;const {id}=await params;const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Messaggio non valido'},{status:400});const {data:row}=await c.admin.from('cases').select('id,organization_id,client_id').eq('id',id).eq('organization_id',c.orgId).maybeSingle();if(!row)return NextResponse.json({error:'Pratica non trovata'},{status:404});const {error}=await c.admin.from('portal_messages').insert({organization_id:c.orgId,case_id:id,client_id:row.client_id,sender_type:'staff',sender_user_id:c.user.id,body:parsed.data.body,public_visible:true});if(error)return NextResponse.json({error:error.message},{status:500});await c.admin.from('notifications').insert({organization_id:c.orgId,case_id:id,client_id:row.client_id,type:'portal.message_sent',message:'Messaggio inviato al cliente nel portale'});await c.admin.from('audit_events').insert({organization_id:c.orgId,actor_user_id:c.user.id,case_id:id,event_type:'portal.message_sent',metadata:{length:parsed.data.body.length}});return NextResponse.json({ok:true})}
