'use client'
import Page from '@/components/Page';import {useEffect,useState} from 'react'
type Member={id:string;user_id:string;role:string;created_at:string;profiles?:{full_name?:string;email?:string}}
export default function Team(){
 const [members,setMembers]=useState<Member[]>([]);const [email,setEmail]=useState('');const [role,setRole]=useState<'admin'|'collaborator'>('collaborator');const [currentRole,setCurrentRole]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [msg,setMsg]=useState('');const [error,setError]=useState('')
 const load=()=>fetch('/api/team').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setMembers(d.members||[]);setCurrentRole(d.currentRole||'')}).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[])
 const add=async()=>{setSaving(true);setError('');setMsg('');try{const r=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,role})});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg('Membro aggiunto.');setEmail('');load()}catch(e){setError(e instanceof Error?e.message:'Errore')}finally{setSaving(false)}}
 const changeRole=async(memberId:string,nextRole:string)=>{setError('');try{const r=await fetch('/api/team',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId,role:nextRole})});const d=await r.json();if(!r.ok)throw Error(d.error);load()}catch(e){setError(e instanceof Error?e.message:'Errore')}}
 const remove=async(memberId:string)=>{if(!window.confirm('Rimuovere questo membro dal team?'))return;setError('');try{const r=await fetch('/api/team',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId})});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg('Membro rimosso.');load()}catch(e){setError(e instanceof Error?e.message:'Errore')}}
 return <Page title="Team" description="Gestisci collaboratori, amministratori e permessi dello studio.">
  {currentRole==='owner'&&<div className="card" style={{marginBottom:18}}><h3 style={{marginTop:0}}>Aggiungi membro</h3><div className='team-invite-grid' style={{display:'grid',gridTemplateColumns:'1fr 180px auto',gap:10}}><input className="search" style={{width:'100%'}} placeholder="email@studio.it" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value as any)} style={{padding:11,border:'1px solid #e4eaf2',borderRadius:10}}><option value="collaborator">Collaboratore</option><option value="admin">Amministratore</option></select><button className="btn primary" disabled={saving||!email} onClick={add}>{saving?'...':'Aggiungi'}</button></div>{msg&&<p style={{color:'#118052',fontWeight:700}}>{msg}</p>}{error&&<p style={{color:'#b42318',fontWeight:700}}>{error}</p>}<p className="muted" style={{fontSize:12}}>L'utente deve avere già un account DocChaser.</p></div>}
  {currentRole!=='owner'&&<div className="card" style={{marginBottom:18}}><b>Permessi team</b><p className="muted" style={{marginBottom:0}}>Puoi visualizzare il team. Solo il proprietario può aggiungere, rimuovere o modificare ruoli.</p></div>}
  <div className="card"><table className="table"><thead><tr><th>Nome</th><th>Email</th><th>Ruolo</th><th>Stato</th>{currentRole==='owner'&&<th>Azioni</th>}</tr></thead><tbody>{loading?<tr><td colSpan={currentRole==='owner'?5:4}>Caricamento...</td></tr>:members.map(m=><tr key={m.id}><td>{m.profiles?.full_name||'Utente'}</td><td>{m.profiles?.email||'—'}</td><td>{m.role==='owner'?'Proprietario':currentRole==='owner'?<select value={m.role} onChange={e=>changeRole(m.id,e.target.value)} style={{padding:7,border:'1px solid #e4eaf2',borderRadius:8}}><option value="admin">Amministratore</option><option value="collaborator">Collaboratore</option></select>:m.role==='admin'?'Amministratore':'Collaboratore'}</td><td><span className="badge green">Attivo</span></td>{currentRole==='owner'&&<td>{m.role!=='owner'&&<button className="btn" onClick={()=>remove(m.id)}>Rimuovi</button>}</td>}</tr>)}</tbody></table>{error&&<p style={{color:'#b42318',fontWeight:700}}>{error}</p>}</div>
 </Page>
}
