import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireSameOrigin } from '@/lib/security'
import { createSupabaseServerClient } from '@/lib/supabase-server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'

const schema=z.object({name:z.string().min(2).max(160),email:z.string().email().max(320),phone:z.string().max(50).optional().nullable(),notes:z.string().max(5000).optional().nullable()})
async function ctx(){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return {error:NextResponse.json({error:'Non autenticato'},{status:401})};const admin=getSupabaseAdmin();if(!admin)return {error:NextResponse.json({error:'Supabase server non configurato'},{status:500})};const {data:member}=await admin.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1).maybeSingle();if(!member)return {error:NextResponse.json({error:'Organizzazione non configurata'},{status:400})};return {admin,orgId:member.organization_id,user}}

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const c=await ctx();if('error'in c)return c.error;const {data:client,error}=await c.admin.from('clients').select('id,name,email,phone,notes,privacy_consent_at,created_at,cases(id,title,status,due_date,updated_at)').eq('id',id).eq('organization_id',c.orgId).is('deleted_at',null).maybeSingle();if(error)return NextResponse.json({error:error.message},{status:500});if(!client)return NextResponse.json({error:'Cliente non trovato'},{status:404});return NextResponse.json({client})}

export async function PUT(req:Request,{params}:{params:Promise<{id:string}>}){const originError=requireSameOrigin(req);if(originError)return originError;const {id}=await params;const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Dati cliente non validi'},{status:400});const c=await ctx();if('error'in c)return c.error;const {data,error}=await c.admin.from('clients').update({name:parsed.data.name,email:parsed.data.email,phone:parsed.data.phone||null,notes:parsed.data.notes||null,updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',c.orgId).is('deleted_at',null).select('id,name,email,phone,notes').maybeSingle();if(error)return NextResponse.json({error:error.message},{status:500});if(!data)return NextResponse.json({error:'Cliente non trovato'},{status:404});return NextResponse.json({client:data})}

export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){const originError=requireSameOrigin(req);if(originError)return originError;const {id}=await params;const c=await ctx();if('error'in c)return c.error;const {data:cases}=await c.admin.from('cases').select('id').eq('client_id',id).eq('organization_id',c.orgId).limit(1);if((cases||[]).length)return NextResponse.json({error:'Impossibile eliminare un cliente con pratiche collegate. Archivialo invece.'},{status:409});const {error}=await c.admin.from('clients').update({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',c.orgId).is('deleted_at',null);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}
