'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {LayoutDashboard,FolderKanban,Users,Files,Clock3,UsersRound,CreditCard,Settings,ScrollText,ShieldCheck,Menu,Search,Bell,X,UserRound,FolderOpen,FileText} from 'lucide-react';
import PublicShell from '@/components/PublicShell';

const items=[['/dashboard','Dashboard',LayoutDashboard],['/onboarding','Setup studio',Settings],['/cases','Pratiche',FolderKanban],['/clients','Clienti',Users],['/templates','Modelli',Files],['/reminders','Reminder',Clock3],['/team','Team',UsersRound],['/billing','Fatturazione',CreditCard],['/settings','Impostazioni',Settings],['/audit','Audit log',ScrollText],['/security','Security',ShieldCheck],['/notifications','Notifiche',Bell]] as const;
const PUBLIC=['/','/login','/register','/recover','/reset-password','/pricing','/features','/faq','/privacy','/terms','/cookies'];
const PORTAL='/portal';

function PrivateShell({children}:{children:React.ReactNode}){
 const path=usePathname(); const [profile,setProfile]=useState<{full_name?:string|null;email?:string|null}>({}); const [menuOpen,setMenuOpen]=useState(false); const [query,setQuery]=useState(''); const [results,setResults]=useState<Array<{type:string;id:string;title:string;subtitle:string;href:string}>>([]); const [searchOpen,setSearchOpen]=useState(false);
 useEffect(()=>{const q=query.trim();if(q.length<2){setResults([]);setSearchOpen(false);return}const t=setTimeout(()=>{fetch('/api/search?q='+encodeURIComponent(q)).then(r=>r.ok?r.json():null).then(d=>{setResults(d?.results||[]);setSearchOpen(true)}).catch(()=>{})},180);return()=>clearTimeout(t)},[query]);
 useEffect(()=>{fetch('/api/settings').then(r=>r.ok?r.json():null).then(d=>{if(d?.profile)setProfile(d.profile)}).catch(()=>{})},[]); useEffect(()=>{setMenuOpen(false)},[path]); useEffect(()=>{document.body.style.overflow=menuOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[menuOpen]);
 const displayName=profile.full_name||profile.email?.split('@')[0]||'Utente'; const initials=displayName.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'DC';
 return <div className="shell"><aside className="sidebar"><div className="brand">Doc<span>Chaser</span></div><nav className="nav">{items.map(([href,label,Icon])=><Link key={href} className={path.startsWith(href)?'active':''} href={href}><Icon size={17}/>{label}</Link>)}</nav></aside>{menuOpen&&<button aria-label="Chiudi menu" className="mobile-backdrop" onClick={()=>setMenuOpen(false)}/>}<aside className={'mobile-drawer '+(menuOpen?'open':'')} aria-hidden={!menuOpen}><div className="mobile-drawer-head"><div className="brand">Doc<span>Chaser</span></div><button className="icon-btn" aria-label="Chiudi menu" onClick={()=>setMenuOpen(false)}><X size={21}/></button></div><nav className="nav">{items.map(([href,label,Icon])=><Link key={href} className={path.startsWith(href)?'active':''} href={href}><Icon size={18}/>{label}</Link>)}</nav><div className="mobile-drawer-footer"><span>{displayName}</span></div></aside><main className="main"><header className="topbar"><button className="menu-btn" aria-label="Apri menu" onClick={()=>setMenuOpen(true)}><Menu size={21}/></button><div className="search-box" style={{position:'relative'}}><Search size={17} color="#64748b"/><input className="search" aria-label="Cerca" value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>query.trim().length>=2&&setSearchOpen(true)} placeholder="Cerca clienti, pratiche, documenti..."/>{searchOpen&&<><button aria-label="Chiudi risultati" onClick={()=>setSearchOpen(false)} style={{border:0,background:'transparent',cursor:'pointer',padding:4}}><X size={15}/></button><div className="global-search-results" role="listbox">{results.length?results.map(r=><Link key={r.type+r.id} href={r.href} onClick={()=>{setSearchOpen(false);setQuery('')}} className="global-search-result"><span className="global-search-icon">{r.type==='client'?<UserRound size={16}/>:r.type==='case'?<FolderOpen size={16}/>:<FileText size={16}/>}</span><span><b>{r.title}</b><small>{r.subtitle}</small></span></Link>):<div className="global-search-empty">Nessun risultato</div>}</div></>}</div><Link className="icon-btn" aria-label="Notifiche" href="/notifications"><Bell size={18}/></Link><div className="profile"><div title={displayName} className="avatar">{initials}</div><div className="mobile-profile-name">{displayName}</div></div></header>{children}</main></div>
}
export default function AppShell({children}:{children:React.ReactNode}){const path=usePathname(); const isPublic=PUBLIC.some(p=>p==='/'?path==='/':path===p||path.startsWith(p+'/')); if(path===PORTAL||path.startsWith(PORTAL+'/')) return <>{children}</>; return isPublic?<PublicShell>{children}</PublicShell>:<PrivateShell>{children}</PrivateShell>}
