import { NextResponse } from 'next/server'
import { z } from 'zod'
import { createSupabaseServerClient } from '@/lib/supabase-server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import { requireSameOrigin } from '@/lib/security'

const itemSchema=z.object({name:z.string().min(1).max(160),description:z.string().max(500).nullable().optional(),required:z.boolean().default(true)})
const workflowSchema=z.object({auto_ai:z.boolean().default(true),missing_email:z.boolean().default(true),correction_email:z.boolean().default(true),completion_email:z.boolean().default(true),reminder_days:z.number().int().min(1).max(30).default(3)})
const createSchema=z.object({name:z.string().min(2).max(160),description:z.string().max(500).optional().default(''),items:z.array(itemSchema).min(1).max(100),workflow:workflowSchema.optional()})
const updateSchema=createSchema.extend({id:z.string().uuid()})

async function ctx(){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return {error:NextResponse.json({error:'Non autenticato'},{status:401})};const admin=getSupabaseAdmin();if(!admin)return {error:NextResponse.json({error:'Supabase server non configurato'},{status:500})};const {data:member}=await admin.from('organization_members').select('organization_id,role').eq('user_id',user.id).limit(1).maybeSingle();if(!member)return {error:NextResponse.json({error:'Organizzazione non configurata'},{status:400})};return {admin,orgId:member.organization_id,user,role:member.role}}
const normalize=(t:any)=>({...t,items:[...(t.template_items||[])].sort((a:any,b:any)=>(a.sort_order??0)-(b.sort_order??0)),workflow:t.workflow_config||{auto_ai:true,missing_email:true,correction_email:true,completion_email:true,reminder_days:3}})

export async function GET(){const c=await ctx();if('error'in c)return c.error;const {data,error}=await c.admin.from('templates').select('id,name,description,created_at,workflow_config,template_items(id,name,description,required,sort_order,allowed_formats,max_files)').eq('organization_id',c.orgId).order('created_at');if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({templates:(data||[]).map(normalize)})}

export async function POST(req:Request){const originError=requireSameOrigin(req);if(originError)return originError;const c=await ctx();if('error'in c)return c.error;if(c.role!=='owner')return NextResponse.json({error:'Solo il proprietario può creare modelli'},{status:403});const parsed=createSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Dati modello non validi'},{status:400});const {data:template,error}=await c.admin.from('templates').insert({organization_id:c.orgId,name:parsed.data.name,description:parsed.data.description,workflow_config:parsed.data.workflow}).select('id,name,description,created_at,workflow_config').single();if(error||!template)return NextResponse.json({error:error?.message||'Impossibile creare il modello'},{status:500});const {error:itemError}=await c.admin.from('template_items').insert(parsed.data.items.map((item,index)=>({template_id:template.id,name:item.name,description:item.description||null,required:item.required,allowed_formats:['application/pdf','image/jpeg','image/png'],max_files:1,sort_order:index})));if(itemError){await c.admin.from('templates').delete().eq('id',template.id).eq('organization_id',c.orgId);return NextResponse.json({error:itemError.message},{status:500})}await c.admin.from('audit_events').insert({organization_id:c.orgId,actor_user_id:c.user.id,event_type:'template.created',metadata:{template_id:template.id}});return NextResponse.json({template},{status:201})}

export async function PUT(req:Request){const originError=requireSameOrigin(req);if(originError)return originError;const c=await ctx();if('error'in c)return c.error;if(c.role!=='owner')return NextResponse.json({error:'Solo il proprietario può modificare modelli'},{status:403});const parsed=updateSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Dati modello non validi'},{status:400});const {id,name,description,items,workflow}=parsed.data;const {data:existing,error:findError}=await c.admin.from('templates').select('id,name,description,workflow_config,template_items(name,description,required,sort_order)').eq('id',id).eq('organization_id',c.orgId).maybeSingle();if(findError)return NextResponse.json({error:findError.message},{status:500});if(!existing)return NextResponse.json({error:'Modello non trovato'},{status:404});const {error:updateError}=await c.admin.from('templates').update({name,description,workflow_config:workflow,updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',c.orgId);if(updateError)return NextResponse.json({error:updateError.message},{status:500});const {error:deleteError}=await c.admin.from('template_items').delete().eq('template_id',id);if(deleteError)return NextResponse.json({error:deleteError.message},{status:500});const {error:itemError}=await c.admin.from('template_items').insert(items.map((item,index)=>({template_id:id,name:item.name,description:item.description||null,required:item.required,allowed_formats:['application/pdf','image/jpeg','image/png'],max_files:1,sort_order:index})));if(itemError)return NextResponse.json({error:itemError.message},{status:500});await c.admin.from('audit_events').insert({organization_id:c.orgId,actor_user_id:c.user.id,event_type:'template.updated',metadata:{template_id:id}});return NextResponse.json({ok:true})}

export async function DELETE(req:Request){const originError=requireSameOrigin(req);if(originError)return originError;const c=await ctx();if('error'in c)return c.error;if(c.role!=='owner')return NextResponse.json({error:'Solo il proprietario può eliminare modelli'},{status:403});const body=await req.json().catch(()=>null);const id=z.string().uuid().safeParse(body?.id);if(!id.success)return NextResponse.json({error:'ID modello non valido'},{status:400});const {count}=await c.admin.from('cases').select('id',{count:'exact',head:true}).eq('template_id',id.data).eq('organization_id',c.orgId);if((count||0)>0)return NextResponse.json({error:'Modello in uso da pratiche esistenti: modificalo invece di eliminarlo.'},{status:409});const {error}=await c.admin.from('templates').delete().eq('id',id.data).eq('organization_id',c.orgId);if(error)return NextResponse.json({error:error.message},{status:500});await c.admin.from('audit_events').insert({organization_id:c.orgId,actor_user_id:c.user.id,event_type:'template.deleted',metadata:{template_id:id.data}});return NextResponse.json({ok:true})}
