'use client'
import { useEffect,useState } from 'react';import {useRouter} from 'next/navigation';import Page from '@/components/Page'
type Client={id:string;name:string;email:string};type Template={id:string;name:string;description?:string}
export default function NewCase(){const r=useRouter();const [clients,setClients]=useState<Client[]>([]);const [templates,setTemplates]=useState<Template[]>([]);const [client,setClient]=useState('');const [template,setTemplate]=useState('');const [dueDate,setDueDate]=useState('');const [name,setName]=useState('');const [email,setEmail]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{fetch('/api/workspace').then(async x=>{const d=await x.json();if(!x.ok)throw new Error(d.error);setClients(d.clients);setTemplates(d.templates);if(d.templates[0])setTemplate(d.templates[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 const addClient=async()=>{setError('');if(!name||!email)return setError('Inserisci nome ed email del cliente.');const res=await fetch('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email})});const d=await res.json();if(!res.ok)return setError(d.error||'Errore cliente');setClients(c=>[...c,d.client]);setClient(d.client.id);setName('');setEmail('')}
 const create=async()=>{setError('');setMessage('');if(!client||!template)return setError('Seleziona cliente e modello.');setSaving(true);try{const res=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:client,templateId:template,dueDate:dueDate||null})});const d=await res.json();if(!res.ok)throw new Error(d.error||'Errore');setMessage(`Pratica creata. ${d.emailSent?'Email inviata al cliente.':'Email non inviata: configura Resend.'}`);setTimeout(()=>r.push(`/cases/${d.case.id}`),900)}catch(e){setError(e instanceof Error?e.message:'Errore')}finally{setSaving(false)}}
 if(loading)return <Page title="Nuova pratica"><div className="card">Caricamento...</div></Page>
 return <Page title="Nuova pratica" description="Crea una checklist e invia al cliente un link sicuro."><div className="card" style={{maxWidth:820}}><label>Cliente</label><select value={client} onChange={e=>setClient(e.target.value)} style={{display:'block',width:'100%',padding:12,border:'1px solid #e4eaf2',borderRadius:10,margin:'7px 0 12px'}}><option value="">Seleziona cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} — {c.email}</option>)}</select><details style={{marginBottom:20}}><summary style={{cursor:'pointer',fontWeight:700}}>+ Crea nuovo cliente</summary><div className='form-grid-2' style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:12}}><input className="search" style={{width:'100%'}} placeholder="Nome e cognome" value={name} onChange={e=>setName(e.target.value)}/><input className="search" style={{width:'100%'}} placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/></div><button className="btn secondary" style={{marginTop:10}} onClick={addClient}>Salva cliente</button></details><label>Modello checklist</label><select value={template} onChange={e=>setTemplate(e.target.value)} style={{display:'block',width:'100%',padding:12,border:'1px solid #e4eaf2',borderRadius:10,margin:'7px 0 18px'}}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><label>Scadenza</label><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} style={{display:'block',width:'100%',padding:12,border:'1px solid #e4eaf2',borderRadius:10,margin:'7px 0 22px'}}/><button className="btn primary" disabled={saving||!client||!template} onClick={create}>{saving?'Creazione...':'Crea e invia pratica'}</button>{message&&<p style={{color:'#118052',fontWeight:700}}>{message}</p>}{error&&<p style={{color:'#b42318',fontWeight:700}}>{error}</p>}<p className="muted" style={{fontSize:12,marginTop:18}}>Il link del portale scade dopo 30 giorni ed è revocabile dallo studio.</p></div></Page>}
