'use client'
import {useState} from 'react'
import Link from 'next/link'
import {useRouter,useSearchParams} from 'next/navigation'

export default function Register(){
 const r=useRouter(); const params=useSearchParams(); const selected=params.get('plan')
 const [fullName,setFullName]=useState('');const [email,setEmail]=useState('');const [studioName,setStudioName]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [done,setDone]=useState(false)
 const submit=async()=>{if(selected&&['starter','studio','team'].includes(selected)){try{localStorage.setItem('docchaser_selected_plan',selected)}catch{}}setBusy(true);setError('');try{const res=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName,email,studioName,password})});const d=await res.json();if(!res.ok)throw new Error(d.error||'Registrazione non riuscita');if(d.requiresEmailConfirmation){setDone(true)}else r.push(selected&&['starter','studio','team'].includes(selected)?`/billing?plan=${selected}`:'/onboarding')}catch(e){setError(e instanceof Error?e.message:'Registrazione non riuscita')}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20}}><div className="card" style={{width:'100%',maxWidth:460}}><div className="brand" style={{padding:0}}>Doc<span>Chaser</span></div><h1>Crea il tuo studio</h1>{selected&&<div className="badge green" style={{marginBottom:14}}>Piano selezionato: {selected.charAt(0).toUpperCase()+selected.slice(1)}</div>}<div style={{display:'grid',gap:10}}><input className="search" style={{width:'100%'}} placeholder="Nome e cognome" value={fullName} onChange={e=>setFullName(e.target.value)}/><input className="search" style={{width:'100%'}} placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="search" style={{width:'100%'}} placeholder="Nome dello studio" value={studioName} onChange={e=>setStudioName(e.target.value)}/><input className="search" style={{width:'100%'}} placeholder="Password (min. 12 caratteri)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></div><button className="btn primary" style={{marginTop:16,width:'100%',justifyContent:'center'}} disabled={busy} onClick={submit}>{busy?'Creazione…':'Crea account'}</button>{error&&<p style={{color:'#b42318'}}>{error}</p>}{done&&<p style={{color:'#118052',fontWeight:700}}>Controlla la tua email per confermare l’account, poi accedi{selected?` e continua con il piano ${selected}.`:'.'}</p>}<p className="muted" style={{fontSize:13,marginTop:14}}>Hai già un account? <Link href="/login">Accedi</Link></p></div></main>
}
