'use client'
import Page from '@/components/Page'
import { useEffect, useState } from 'react'
export default function Settings(){
 const [form,setForm]=useState({name:'',retentionDays:365,aiEnabled:true}); const [role,setRole]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('')
 useEffect(()=>{fetch('/api/settings').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setForm({name:d.organization?.name||'',retentionDays:d.organization?.retention_days||365,aiEnabled:d.organization?.ai_enabled!==false});setRole(d.role||'')}).catch(e=>setError(e.message))},[])
 async function save(){setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Impostazioni salvate.')}catch(e){setError(e instanceof Error?e.message:'Errore')}finally{setBusy(false)}}
 return <Page title="Impostazioni" description="Gestisci organizzazione, conservazione dati e preferenze AI."><div className="card" style={{maxWidth:760,display:'grid',gap:18}}><div><label>Nome studio</label><input value={form.name} disabled={role!=='owner'} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label>Giorni di conservazione</label><input type="number" min={30} max={3650} value={form.retentionDays} disabled={role!=='owner'} onChange={e=>setForm({...form,retentionDays:Number(e.target.value)})}/><small className="muted">Da 30 a 3650 giorni.</small></div><label style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span><b>Analisi AI</b><br/><small className="muted">L'AI analizza i documenti ma non li approva o rifiuta automaticamente.</small></span><input style={{width:20}} type="checkbox" checked={form.aiEnabled} disabled={role!=='owner'} onChange={e=>setForm({...form,aiEnabled:e.target.checked})}/></label><button className="btn primary" disabled={busy||role!=='owner'} onClick={save}>{busy?'Salvataggio…':'Salva impostazioni'}</button>{role!=='owner'&&<p className="muted">Solo il proprietario dello studio può modificare queste impostazioni.</p>}{message&&<span className="badge green">{message}</span>}{error&&<span className="badge red">{error}</span>}</div></Page>
}
