import { NextResponse } from 'next/server'
import { createHash } from 'crypto'
import { z } from 'zod'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import { rateLimit } from '@/lib/security'
const schema=z.object({body:z.string().trim().min(1).max(4000)})
async function getCase(token:string){const admin=getSupabaseAdmin();if(!admin)return null;const hash=createHash('sha256').update(token).digest('hex');const {data}=await admin.from('cases').select('id,organization_id,client_id,public_token_expires_at,public_token_revoked_at').eq('public_token_hash',hash).maybeSingle();if(!data||data.public_token_revoked_at||(data.public_token_expires_at&&new Date(data.public_token_expires_at)<=new Date()))return null;return{admin,row:data}}
export async function GET(_req:Request,{params}:{params:Promise<{token:string}>}){const {token}=await params;const c=await getCase(token);if(!c)return NextResponse.json({error:'Portale non valido o scaduto'},{status:404});const {data,error}=await c.admin.from('portal_messages').select('id,sender_type,body,created_at').eq('case_id',c.row.id).eq('public_visible',true).order('created_at',{ascending:true}).limit(100);if(error)return NextResponse.json({error:'Messaggi non disponibili'},{status:500});return NextResponse.json({messages:data||[]})}
export async function POST(req:Request,{params}:{params:Promise<{token:string}>}){const limited=rateLimit(req,'portal-messages',10,60*60*1000);if(limited)return limited;const {token}=await params;const c=await getCase(token);if(!c)return NextResponse.json({error:'Portale non valido o scaduto'},{status:404});const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Messaggio non valido'},{status:400});const {error}=await c.admin.from('portal_messages').insert({organization_id:c.row.organization_id,case_id:c.row.id,client_id:c.row.client_id,sender_type:'client',body:parsed.data.body,public_visible:true});if(error)return NextResponse.json({error:'Invio messaggio non riuscito'},{status:500});await c.admin.from('notifications').insert({organization_id:c.row.organization_id,case_id:c.row.id,client_id:c.row.client_id,type:'portal.message_received',message:'Nuovo messaggio ricevuto dal cliente nel portale'});return NextResponse.json({ok:true})}
