import { NextResponse } from 'next/server'
import { randomBytes, createHash } from 'crypto'
import { z } from 'zod'
import { createSupabaseServerClient } from '@/lib/supabase-server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import { requireSameOrigin, rateLimit } from '@/lib/security'
const schema=z.object({action:z.enum(['portal','missing','correction','complete']),note:z.string().max(2000).optional().default('')})
const esc=(v:string)=>v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')
async function ctx(){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:NextResponse.json({error:'Autenticazione richiesta'},{status:401})};const admin=getSupabaseAdmin();if(!admin)return{error:NextResponse.json({error:'Supabase server non configurato'},{status:503})};const {data:member}=await admin.from('organization_members').select('organization_id,role').eq('user_id',user.id).limit(1).maybeSingle();if(!member)return{error:NextResponse.json({error:'Organizzazione non configurata'},{status:403})};if(!['owner','admin'].includes(member.role))return{error:NextResponse.json({error:'Permesso insufficiente'},{status:403})};return{admin,orgId:member.organization_id,user}}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const originError=requireSameOrigin(req);if(originError)return originError;const limited=rateLimit(req,'case-communications',30,60*60*1000);if(limited)return limited;const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Azione non valida'},{status:400});const c=await ctx();if('error'in c)return c.error;const {id}=await params;const{admin,orgId,user}=c;const{data:row,error}=await admin.from('cases').select('id,title,status,due_date,client_id,clients(id,name,email),case_items(id,name,required,status,documents(id,original_name,status))').eq('id',id).eq('organization_id',orgId).maybeSingle();if(error)return NextResponse.json({error:error.message},{status:500});if(!row)return NextResponse.json({error:'Pratica non trovata'},{status:404});const client=Array.isArray((row as any).clients)?(row as any).clients[0]:(row as any).clients;if(!client?.email)return NextResponse.json({error:'Email cliente mancante'},{status:400});if(!process.env.RESEND_API_KEY||!process.env.RESEND_FROM_EMAIL)return NextResponse.json({error:'Email non configurata'},{status:503});
const base=(process.env.NEXT_PUBLIC_APP_URL||new URL(req.url).origin).replace(/\/$/,'');const token=randomBytes(32).toString('base64url');const hash=createHash('sha256').update(token).digest('hex');const expires=new Date(Date.now()+30*24*60*60*1000).toISOString();const portalUrl=`${base}/portal/${token}`;if(parsed.data.action!=='complete'){const{error:e}=await admin.from('cases').update({public_token_hash:hash,public_token_expires_at:expires,public_token_revoked_at:null,updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',orgId);if(e)return NextResponse.json({error:e.message},{status:500})}
const items=(row as any).case_items||[];const missing=items.filter((i:any)=>i.required&&!(i.documents||[]).some((d:any)=>['verified','uploaded','ai_review'].includes(d.status)));const corrections=items.filter((i:any)=>i.status==='needs_correction'||(i.documents||[]).some((d:any)=>d.status==='revision_requested'));const action=parsed.data.action;let subject='',intro='',detail='';if(action==='portal'){subject=`Documenti richiesti — ${row.title}`;intro='Lo studio ti ha richiesto di completare la documentazione della pratica.';detail='Apri il portale sicuro per caricare i documenti.'}if(action==='missing'){subject=`Documenti mancanti — ${row.title}`;intro='Ti ricordiamo che alcuni documenti della pratica non risultano ancora ricevuti.';detail=missing.length?`<ul>${missing.map((x:any)=>`<li>${esc(x.name)}</li>`).join('')}</ul>`:'Non risultano documenti obbligatori mancanti.'}if(action==='correction'){subject=`Correzione documenti richiesta — ${row.title}`;intro='Lo studio ha richiesto una correzione o un nuovo caricamento per alcuni documenti.';detail=corrections.length?`<ul>${corrections.map((x:any)=>`<li>${esc(x.name)}</li>`).join('')}</ul>`:'Controlla il portale per i dettagli della richiesta.'}if(action==='complete'){subject=`Pratica completata — ${row.title}`;intro='La documentazione richiesta per la pratica risulta completata.';detail='Non è necessario effettuare ulteriori caricamenti, salvo diversa comunicazione dello studio.'}const note=parsed.data.note.trim();const html=`<p>Ciao ${esc(client.name||'')},</p><p>${intro}</p>${detail}${note?`<p><b>Nota dello studio:</b> ${esc(note)}</p>`:''}${action!=='complete'?`<p><a href="${esc(portalUrl)}">Apri il portale sicuro</a></p><p>Il link è valido 30 giorni.</p>`:''}<p>Grazie.</p>`;const text=`Ciao ${client.name||''},\n\n${intro}\n${action!=='complete'?`\nPortale: ${portalUrl}\n`:''}${note?`\nNota: ${note}\n`:''}`;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM_EMAIL,to:[client.email],subject,html,text})});if(!response.ok)return NextResponse.json({error:'Invio email non riuscito'},{status:502});await admin.from('notifications').insert({organization_id:orgId,case_id:id,client_id:row.client_id,type:`communication.${action}`,message:`${subject} inviato a ${client.email}`});await admin.from('audit_events').insert({organization_id:orgId,actor_user_id:user.id,case_id:id,event_type:`communication.${action}`,metadata:{to:client.email,action,note:note||null}});return NextResponse.json({ok:true,action,to:client.email,subject,portalUrl:action==='complete'?null:portalUrl})}
