'use client'
import Link from 'next/link'
import { CheckCircle2, Clock3, AlertTriangle, FileSearch, Mail, Plus, ArrowUpRight, Bell, RefreshCw, CalendarClock } from 'lucide-react'
import { useEffect, useState } from 'react'

type DashboardData={stats:{clients:number;cases:number;required:number;uploaded:number;verified:number;needsReview:number;corrections:number;dueSoon:number;overdue:number;complete:number};cases:any[];audits:any[];notifications:any[];reminders:any[];riskCases:any[]}
const labels:Record<string,string>={'document.approved':'Documento approvato','document.revision_requested':'Correzione richiesta','case.created':'Pratica creata','case.portal_sent':'Portale inviato','case.portal_not_sent':'Portale non inviato'}
const fmt=(d:string)=>new Date(d).toLocaleDateString('it-IT',{day:'2-digit',month:'2-digit',year:'numeric'})
export default function Dashboard(){
 const [data,setData]=useState<DashboardData|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 const load=()=>{setLoading(true);fetch('/api/dashboard').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
 useEffect(()=>{load()},[])
 if(error)return <div className="content"><div className="card" style={{color:'#b42318'}}><b>Non riesco a caricare la dashboard.</b><div style={{marginTop:6}}>{error}</div><button className="btn secondary" style={{marginTop:14}} onClick={load}><RefreshCw size={15}/> Riprova</button></div></div>
 if(!data)return <div className="content"><div style={{marginBottom:24}}><div className="skeleton" style={{width:240,height:34}}/><div className="skeleton" style={{width:380,maxWidth:'80%',height:14,marginTop:10}}/></div><div className="grid4"><div className="card"><div className="skeleton" style={{width:90,height:14}}/><div className="skeleton" style={{width:70,height:32,marginTop:12}}/></div><div className="card"><div className="skeleton" style={{width:90,height:14}}/><div className="skeleton" style={{width:70,height:32,marginTop:12}}/></div><div className="card"><div className="skeleton" style={{width:90,height:14}}/><div className="skeleton" style={{width:70,height:32,marginTop:12}}/></div><div className="card"><div className="skeleton" style={{width:90,height:14}}/><div className="skeleton" style={{width:70,height:32,marginTop:12}}/></div></div></div>
 const s=data.stats,pct=s.required?Math.round(s.verified/s.required*100):0
 return <div className="content">
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,marginBottom:24}}><div><div className="badge blue" style={{marginBottom:9}}>Workspace</div><div className="h1">Dashboard operativa</div><div className="muted" style={{marginTop:7}}>Tutto ciò che richiede attenzione, in un'unica schermata.</div></div><div style={{display:'flex',gap:8}}><button className="btn secondary" onClick={load} disabled={loading}><RefreshCw size={15}/> Aggiorna</button><Link className="btn primary" href="/cases/new"><Plus size={17}/> Nuova pratica</Link></div></div>
  <div className="grid4" style={{marginBottom:18}}>{[['Clienti',s.clients,FileSearch],['Pratiche',s.cases,FileSearch],['Da verificare',s.needsReview,Clock3],['Da correggere',s.corrections,AlertTriangle],['Complete',s.complete,CheckCircle2]].map(([label,value,Icon]:any)=><div className="card stat" key={label}><div className="muted" style={{display:'flex',alignItems:'center',gap:6}}><Icon size={15}/>{label}</div><div className="num">{value}</div></div>)}</div>
  <div className="grid2" style={{marginBottom:18}}>
   <div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{marginTop:0}}>⚠️ Priorità operative</h3><span className="badge blue">{data.riskCases.length}</span></div>{data.riskCases.slice(0,7).map((c:any)=><div key={c.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:'13px 0',borderBottom:'1px solid #e4eaf2'}}><div><Link href={`/cases/${c.id}`}><b>{c.title}</b></Link><div className="muted" style={{fontSize:12}}>{c.client?.name||'Cliente'} · {c.reason}</div></div><div style={{textAlign:'right'}}>{c.due_date&&<div className="muted" style={{fontSize:11}}><CalendarClock size={12} style={{verticalAlign:'-2px'}}/> {fmt(c.due_date)}</div>}<Link className="btn secondary" href={`/cases/${c.id}`} style={{marginTop:5}}>Apri <ArrowUpRight size={14}/></Link></div></div>)}{!data.riskCases.length&&<p className="muted">Nessuna pratica critica al momento.</p>}</div>
   <div className="card"><h3 style={{marginTop:0}}>Stato documenti</h3><div style={{display:'flex',alignItems:'center',gap:24,margin:'22px 0'}}><div style={{width:130,height:130,borderRadius:'50%',background:`conic-gradient(#18b981 0 ${pct}%,#e8edf4 ${pct}% 100%)`,display:'grid',placeItems:'center'}}><div style={{width:94,height:94,borderRadius:'50%',background:'#fff',display:'grid',placeItems:'center',fontWeight:800,fontSize:20}}>{pct}%</div></div><div style={{flex:1}}><div style={{display:'flex',justifyContent:'space-between',padding:'8px 0'}}><span>Caricati</span><b>{s.uploaded}/{s.required}</b></div><div style={{display:'flex',justifyContent:'space-between',padding:'8px 0'}}><span>Approvati</span><b>{s.verified}</b></div><div style={{display:'flex',justifyContent:'space-between',padding:'8px 0'}}><span>Scadenze ≤ 7 giorni</span><b>{s.dueSoon}</b></div><div style={{display:'flex',justifyContent:'space-between',padding:'8px 0'}}><span>Scadute</span><b style={{color:s.overdue?'#b42318':undefined}}>{s.overdue}</b></div></div></div><div className="muted" style={{fontSize:12}}>La percentuale considera solo i documenti obbligatori.</div></div>
  </div>
  <div className="grid2">
   <div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{marginTop:0}}>Attività recenti</h3><div style={{display:'flex',gap:12}}><Link href="/reports/analytics" style={{fontSize:12,color:'#126eea'}}>Analytics →</Link><Link href="/audit" style={{fontSize:12,color:'#126eea'}}>Vedi audit →</Link></div></div>{data.audits.slice(0,8).map((a:any)=><div key={a.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'10px 0',borderBottom:'1px solid #e4eaf2'}}><div><b style={{fontSize:13}}>{labels[a.event_type]||a.event_type}</b><div className="muted" style={{fontSize:11}}>{a.metadata?.note||''}</div></div><span className="muted" style={{fontSize:11}}>{new Date(a.created_at).toLocaleString('it-IT')}</span></div>)}{!data.audits.length&&<p className="muted">Nessuna attività.</p>}</div>
   <div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{marginTop:0}}>Centro notifiche</h3><Link href="/notifications" style={{fontSize:12,color:'#126eea'}}>Apri centro →</Link></div>{data.notifications.slice(0,6).map((n:any)=><div key={n.id} style={{padding:'10px 0',borderBottom:'1px solid #e4eaf2'}}><div style={{display:'flex',gap:8,alignItems:'center'}}><Bell size={14}/><b style={{fontSize:13}}>{n.type}</b></div><div className="muted" style={{fontSize:12,marginTop:3}}>{n.message}</div><div className="muted" style={{fontSize:10,marginTop:3}}>{new Date(n.created_at).toLocaleString('it-IT')}</div></div>)}{!data.notifications.length&&<p className="muted">Nessuna notifica.</p>}</div>
  </div>
  <div className="card" style={{marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{marginTop:0}}>Reminder</h3><Link href="/reminders" style={{fontSize:12,color:'#126eea'}}>Gestisci →</Link></div>{data.reminders.slice(0,6).map((r:any)=><div key={r.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'10px 0',borderBottom:'1px solid #e4eaf2'}}><div><b style={{fontSize:13}}>{r.cases?.title||'Pratica'}</b><div className="muted" style={{fontSize:11}}>{r.paused?'In pausa':`${r.sends_count}/${r.max_sends} inviati`}</div></div><span className="badge blue"><Mail size={12}/> {r.last_sent_at?'Attivo':'In attesa'}</span></div>)}{!data.reminders.length&&<p className="muted">Nessun reminder configurato.</p>}</div>
 </div>
}
