'use client'
import Page from '@/components/Page'
import {useEffect,useState} from 'react'

type Item={id?:string;name:string;description?:string|null;required:boolean}
type Workflow={auto_ai:boolean;missing_email:boolean;correction_email:boolean;completion_email:boolean;reminder_days:number}
type Template={id:string;name:string;description:string|null;items:Item[];workflow:Workflow}
const blankWorkflow=():Workflow=>({auto_ai:true,missing_email:true,correction_email:true,completion_email:true,reminder_days:3})

export default function Templates(){
 const [templates,setTemplates]=useState<Template[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [editing,setEditing]=useState<string|null>(null);const [name,setName]=useState('');const [description,setDescription]=useState('');const [items,setItems]=useState<Item[]>([]);const [workflow,setWorkflow]=useState<Workflow>(blankWorkflow());
 const load=()=>fetch('/api/templates').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setTemplates(d.templates||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[])
 const reset=()=>{setEditing(null);setName('');setDescription('');setItems([]);setWorkflow(blankWorkflow())}
 const startEdit=(t:Template)=>{setEditing(t.id);setName(t.name);setDescription(t.description||'');setItems(t.items.map(i=>({id:i.id,name:i.name,description:i.description||'',required:i.required})));setWorkflow({...blankWorkflow(),...(t.workflow||{})});setMessage('');setError('')}
 const addItem=()=>setItems(x=>[...x,{name:'',description:'',required:true}])
 const updateItem=(i:number,p:Partial<Item>)=>setItems(x=>x.map((it,n)=>n===i?{...it,...p}:it))
 const move=(i:number,dir:-1|1)=>setItems(x=>{const n=i+dir;if(n<0||n>=x.length)return x;const a=[...x];[a[i],a[n]]=[a[n],a[i]];return a})
 const remove=(i:number)=>setItems(x=>x.filter((_,n)=>n!==i))
 const save=async()=>{setError('');setMessage('');if(!name.trim())return setError('Inserisci il nome del modello.');if(!items.length||items.some(i=>!i.name.trim()))return setError('Ogni documento deve avere un nome.');setSaving(true);try{const payload={id:editing,name:name.trim(),description:description.trim(),items:items.map(i=>({name:i.name.trim(),description:i.description?.trim()||null,required:i.required})),workflow};const r=await fetch('/api/templates',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?payload:{...payload})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(editing?'Modello aggiornato.':'Modello creato.');reset();await load()}catch(e){setError(e instanceof Error?e.message:'Errore')}finally{setSaving(false)}}
 const removeTemplate=async(id:string)=>{if(!confirm('Eliminare questo modello?'))return;setError('');try{const r=await fetch('/api/templates',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Modello eliminato.');await load()}catch(e){setError(e instanceof Error?e.message:'Errore')}
 }
 return <Page title="Modelli" description="Costruisci checklist riutilizzabili e definisci cosa deve fare automaticamente DocChaser.">
  {message&&<div className="card" style={{marginBottom:14,color:'#118052',borderColor:'#bfe8d2'}}>{message}</div>}{error&&<div className="card" style={{marginBottom:14,color:'#b42318',borderColor:'#f0b5ae'}}>{error}</div>}
  <div className="grid2">
   <div className="card"><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><h3 style={{marginTop:0}}>Modelli disponibili</h3><button className="btn secondary" onClick={()=>{reset();setError('');setMessage('')}}>+ Nuovo</button></div>
    {loading?<p className="muted">Caricamento...</p>:templates.map(t=><div key={t.id} style={{padding:'15px 0',borderBottom:'1px solid #e4eaf2'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><b>{t.name}</b><div className="muted" style={{fontSize:12,marginTop:3}}>{t.items.length} documenti · AI {t.workflow.auto_ai?'attiva':'disattivata'}</div></div><div style={{display:'flex',gap:7}}><button className="btn secondary" onClick={()=>startEdit(t)}>Modifica</button><button className="btn ghost" onClick={()=>removeTemplate(t.id)}>Elimina</button></div></div>{t.description&&<div className="muted" style={{fontSize:12,marginTop:5}}>{t.description}</div>}</div>)}{!loading&&!templates.length&&<p className="muted">Nessun modello disponibile.</p>}
   </div>
   <div className="card"><h3 style={{marginTop:0}}>{editing?'Modifica modello':'Crea modello'}</h3><label>Nome</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Es. Dichiarazione dei redditi"/><label style={{marginTop:12}}>Descrizione</label><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrizione facoltativa"/>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:20}}><div><h4 style={{margin:0}}>Checklist documenti</h4><div className="muted" style={{fontSize:12}}>Ordina i documenti come vuoi mostrarli al cliente.</div></div><button className="btn secondary" onClick={addItem}>+ Documento</button></div>
    <div style={{display:'grid',gap:9,marginTop:12}}>{items.map((item,i)=><div key={i} style={{border:'1px solid #e4eaf2',borderRadius:12,padding:11}}><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><input value={item.name} onChange={e=>updateItem(i,{name:e.target.value})} placeholder="Nome documento"/><div style={{display:'flex',gap:5}}><button className="btn ghost" title="Su" onClick={()=>move(i,-1)}>↑</button><button className="btn ghost" title="Giù" onClick={()=>move(i,1)}>↓</button><button className="btn ghost" onClick={()=>remove(i)}>×</button></div></div><div style={{display:'flex',gap:12,alignItems:'center',marginTop:8}}><input value={item.description||''} onChange={e=>updateItem(i,{description:e.target.value})} placeholder="Descrizione (facoltativa)"/><label style={{display:'flex',alignItems:'center',gap:6,whiteSpace:'nowrap',fontSize:12}}><input type="checkbox" checked={item.required} onChange={e=>updateItem(i,{required:e.target.checked})} style={{width:'auto'}}/> Obbligatorio</label></div></div>)}</div>
    <div style={{marginTop:22,paddingTop:18,borderTop:'1px solid #e4eaf2'}}><h4 style={{margin:'0 0 4px'}}>Workflow automatico</h4><div className="muted" style={{fontSize:12,marginBottom:12}}>Queste regole verranno usate quando esegui il workflow della pratica.</div>{[['auto_ai','Analizza automaticamente i nuovi documenti con AI'],['missing_email','Invia email per documenti mancanti'],['correction_email','Invia email per richieste di correzione'],['completion_email','Invia email quando la pratica è completa']].map(([key,label])=><label key={key} style={{display:'flex',alignItems:'center',gap:9,padding:'7px 0',fontWeight:600}}><input type="checkbox" checked={(workflow as any)[key]} onChange={e=>setWorkflow(w=>({...w,[key]:e.target.checked}))} style={{width:'auto'}}/> {label}</label>)}<div style={{marginTop:9}}><label>Giorni prima del reminder</label><input type="number" min={1} max={30} value={workflow.reminder_days} onChange={e=>setWorkflow(w=>({...w,reminder_days:Math.min(30,Math.max(1,Number(e.target.value)||1))}))} style={{maxWidth:140}}/></div></div>
    <div style={{display:'flex',gap:8,marginTop:20}}><button className="btn primary" disabled={saving||!items.length} onClick={save}>{saving?'Salvataggio...':editing?'Salva modifiche':'Crea modello'}</button>{editing&&<button className="btn ghost" onClick={reset}>Annulla</button>}</div>
   </div>
  </div>
 </Page>
}
